services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - test-network
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    networks:
      - test-network

volumes:
  mysql-data:

networks:
  test-network:
    driver: bridge
